[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -m gunicorn -c /app/gunicorn.conf.py server:app --pythonpath /app/dexy"
healthcheckPath = "/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[mounts]]
source = "data"
destination = "/data" 